### ISSUE TITLE
Startup Issues & Environ key issue & Server Running Issue 

### ISSUE THREAD

**Issue by sherlocksecurity** [BitTheByte/Monitorizer#18]
Hey Mates, 

Eventhough i've dnsrecon and sublist3r installed and running getting some errors. Along with that getting key error where it is fetching some SERVER_FD value not sure how to set it or how we're deducting it. 

Additionally, the slack even subscription is unable to reach the mentioned IP that started by the tool, even i have setup the inbound rules for 6500, 80, 443 as well. 

```
[12/07/2023 11:07:38][ERROR] Unable to execute sublist3r make sure to install all requirements
[12/07/2023 11:07:38][ERROR] Unable to execute dnsrecon make sure to install all requirements
[12/07/2023 11:07:40][INFO ] Continuous scanner is enabled
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/Monitorizer/modules/server/server.py", line 223, in _server
    app.run(debug=False, port=args.port, host='0.0.0.0')
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1191, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 1035, in run_simple
    fd = int(os.environ["WERKZEUG_SERVER_FD"])
  File "/usr/lib64/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'WERKZEUG_SERVER_FD'

[12/07/2023 11:07:40][INFO ] Started event server at http://43.204.109.233:6500/slack
```

**Comment by sherlocksecurity** [comment]
Resolved the WERKZEUG_SERVER_FD issue, able to bring up the host in-app mentions 

> For WERKZEUG_SERVER_FD 
 Removed the `WERKZEUG` module completely and install the old model using `pip3 install werkzeug==2.0.0`

> For Flask Error 
Removed the latest `flask` and install the old flask version that is compatible with the WERKZEUG by 

`pip3 install flask==2.1.3`

**Comment by sherlocksecurity** [comment]
Still the [12/07/2023 11:34:42][ERROR] Unable to execute sublist3r make sure to install all requirements
[12/07/2023 11:34:42][ERROR] Unable to execute dnsrecon make sure to install all requirements error persists and but the scan is running on.
